steps:
# Build the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/burner-ravk/rjesus/rjesus/rjesus:$COMMIT_SHA', '.']
# Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/burner-ravk/rjesus/rjesus/rjesus:$COMMIT_SHA']
# Deploy image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: 
    - 'run'
    - 'deploy'
    - 'rjesus'
    - '--image'
    - 'us-central1-docker.pkg.dev/burner-ravk/rjesus/rjesus/rjesus:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-secrets=FLASK_SECRET_KEY=cricket-tracker-service-flask-secret-key:latest'
images:
- 'us-central1-docker.pkg.dev/burner-ravk/rjesus/rjesus/rjesus:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET